imports ="""//autogenerated
package edu.rutgers.elearning.component.journalism.pte;

import java.util.Random;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

import edu.rutgers.elearning.component.journalism.dao.*;
import edu.rutgers.elearning.component.pte.ProblemTemplateEngine;
import edu.rutgers.elearning.component.questions.GeneratedQuestion;
import edu.rutgers.elearning.component.questions.QuestionAnswer;
import edu.rutgers.elearning.component.questions.RegexQuestion;
import edu.rutgers.elearning.util.math.SigfigNumber;
import edu.rutgers.elearning.component.journalism.model.*;
import edu.rutgers.elearning.component.journalism.model.SubjectModel.Gender;
"""

DAOs ="""
SubjectDAO subjectAccess = new SubjectDAO();
Random rand = new Random();
"""
def generateClassName(name):
    return """
public class {name} extends ProblemTemplateEngine {{
""".format(name=name)

def generateConstructorName(name):
    return """
public {name}(int problemtemplate_id, int[] criticalskill_ids, int debugmode, QuestionType type) {{
\tsuper(problemtemplate_id, criticalskill_ids, debugmode, type);
""".format(name=name)

def generateMiddleFiller():
    return """
/**
	 * Formats the answers from a SigfigNumber into a
	 * QuestionAnswer object. Answers passed to this method
	 * can either be correct or incorrect answers.
	 *
	 * @param answer - The answer to be displayed
	 * @param correct - true if this is the correct answer, otherwise false
	 * @return QuestionAnswer - Answer to be displayed to the user as one
	 * 		   of the multiple choice options
	 */
	protected QuestionAnswer formatAnswer(SigfigNumber answer, boolean correct) {
		return null; //this isn't needed for open answer
	}

	/**
	 * Populates the multiple choice answers, typically
	 * one correct answer and four incorrect answers. If
	 * five answers are not defined, this method will generate
	 * answers similar to the correct answer.
	 *
	 * @return List&lt;QuestionAnswer&gt; - the answers to be displayed
	 * 		   to the users.
	 */
	public List<QuestionAnswer> getMultipleChoiceAnswers() {
		return null; //this isn't needed for open answer
	}

	/**
	 * Used to generate the question text displayed.
	 *
	 * @return question - String question, this will be
	 * 		   displayed to the user
	 */
	public String getQuestionText() {
            return chosenSentenceDistractor;
        }

	@Override
	/**
	 * Serves the question to the user. Depending on
	 * the type variable, this method will either
	 * serve a multiple choice question or an open
	 * answer question.
	 *
	 * @return GeneratedQuestion - object used to display
	 * 		   a multiple choice or open answer question
	 */
	public GeneratedQuestion serveQuestion() {
		RegexQuestion rq = new RegexQuestion();
		if (type == QuestionType.OPENANSWER) {
			rq.setRegex_accept(chosenSentenceAnswer);
			//gq.setRegex_reject(null);
		}
		if (rq != null) {
			rq.setQuestion_text(getQuestionText());
			rq.loadMetadata(problemtemplate_id);
			//gq.setDifficulty(difficulty);
			// TODO add critical skills
		}
		return rq;
	}

	public String storeDistractors()
	{
		HashMap<String, Object> dataMap = new HashMap<String, Object>();

		//not sure how to deal with this yet

		return dataMap.toString();
	}

	/**
	 * This method is for the 2018 Math Placement Exam.
	 * This method is to store the question data for a reporting
	 * service. This method will return a listing of all variables
	 * in this PTE
	 *
	 * @return String the version
	 */
	public String storeVersion()
	{
		HashMap<String, Object> dataMap = new HashMap<String, Object>();

                //TODO: this

		return dataMap.toString();
	}

	@Override
	public String getDebugInfo() {
		// TODO Auto-generated method stub
		return null;
	}

}

"""

def generateVersion(name):
    return """

    """

def generateEnd():
    return """

    """
